name: catgpt
run-name: ${{ github.actor }} is building catgpt
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Build image
        run: make docker-build